# Generated by Django 3.2.16 on 2023-04-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_sightgroup_is_pub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sight',
            options={'ordering': ('title',), 'verbose_name': 'Достопримечательность', 'verbose_name_plural': 'Достопримечательности'},
        ),
        migrations.AlterField(
            model_name='sightgroup',
            name='tourism_type',
            field=models.CharField(choices=[('museum', 'музейный туризм'), ('spa', 'оздоровительный туризм'), ('beach', 'пляжный туризм'), ('industry', 'промышленный туризм'), ('outdoor', 'развлекательный туризм'), ('pilgrimage', 'религиозный туризм'), ('extreme', 'спортивный туризм'), ('theatre', 'театральный туризм'), ('shopping', 'шопинг-туризм'), ('recreation', 'экологический туризм'), ('excursion', 'экскурсионный туризм')], default='recreation', max_length=10, verbose_name='Вид туризма'),
        ),
    ]
