# Generated by Django 3.2.16 on 2023-04-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20230402_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='paths',
        ),
        migrations.RemoveField(
            model_name='region',
            name='polygons',
        ),
    ]
