# Generated by Django 3.2.16 on 2023-04-23 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20230423_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_sights', to='geo.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_sights', to='geo.sightgroup', verbose_name='Группы'),
        ),
    ]
