# Generated by Django 3.2.16 on 2023-07-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_auto_20230710_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightgroup',
            name='tourism_type',
            field=models.CharField(choices=[('gastro', 'гастротуризм'), ('museum', 'музейный туризм'), ('spa', 'оздоровительный туризм'), ('beach', 'пляжный туризм'), ('industry', 'промышленный туризм'), ('outdoor', 'развлекательный туризм'), ('pilgrimage', 'религиозный туризм'), ('extreme', 'спортивный туризм'), ('theatre', 'театральный туризм'), ('shopping', 'шопинг-туризм'), ('recreation', 'экологический туризм'), ('excursion', 'экскурсионный туризм')], default='recreation', max_length=10, verbose_name='Вид туризма'),
        ),
    ]
