# Generated by Django 3.2.16 on 2023-07-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_alter_sightgroup_tourism_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('title',), 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
    ]
