# Generated by Django 3.2.16 on 2023-09-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_alter_region_options'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='sight',
        #     name='group',
        # ),
        migrations.AddField(
            model_name='sight',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_sights', to='geo.SightGroup', verbose_name='Группы'),
        ),
    ]
