# Generated by Django 3.2.16 on 2023-09-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_auto_20230921_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='group',
            field=models.ManyToManyField(related_name='group_sights', to='geo.SightGroup', verbose_name='Группы'),
        ),
    ]
