# Generated by Django 3.2.16 on 2023-09-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_alter_sight_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightgroup',
            name='name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Имя'),
        ),
    ]
