# Generated by Django 4.2.17 on 2025-01-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0011_alter_sightgroup_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sight",
            name="additional_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
