# Generated by Django 4.2.17 on 2025-03-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0012_sight_additional_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="sight",
            name="is_kernel_checked",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Ядро проверено"
            ),
        ),
        migrations.AddField(
            model_name="sight",
            name="similarity_rate",
            field=models.FloatField(
                default=0.0, verbose_name="Схожесть запроса и ядра"
            ),
        ),
    ]
