# Generated by Django 4.2.17 on 2025-03-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0013_sight_is_kernel_checked_sight_similarity_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="sight",
            name="is_network",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Сеть"
            ),
        ),
    ]
