# Generated by Django 4.2.16 on 2025-04-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0014_sight_is_network"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sight",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="sight",
            name="is_archive",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Архив"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sight",
            unique_together={
                (
                    "name",
                    "full_name",
                    "city",
                    "is_pub",
                    "code",
                    "lat",
                    "lon",
                    "is_network",
                    "is_archive",
                )
            },
        ),
    ]
