# Generated by Django 4.2.16 on 2025-04-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0015_alter_sight_unique_together_sight_is_archive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="federal_district",
            field=models.CharField(
                choices=[
                    ("ЦФО", "Центральный"),
                    ("СЗФО", "Северо-Западный"),
                    ("ЮФО", "Южный"),
                    ("СКФО", "Северо-Кавказский"),
                    ("ПФО", "Приволжский"),
                    ("УрФО", "Уральский"),
                    ("СФО", "Сибирский"),
                    ("ДФО", "Дальневосточный"),
                ],
                default="",
                max_length=4,
                verbose_name="Федеральный округ",
            ),
            preserve_default=False,
        ),
    ]
