# Generated by Django 4.2.16 on 2026-06-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0016_region_federal_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="rank_change",
            field=models.IntegerField(default=0, verbose_name="Изменение ранга"),
        ),
        migrations.AlterField(
            model_name="region",
            name="rank",
            field=models.IntegerField(
                choices=[
                    (0, "Начальный"),
                    (1, "Низкий"),
                    (2, "Средний"),
                    (3, "Высокий"),
                    (4, "Лидер"),
                ],
                default=0,
                verbose_name="Ранг",
            ),
        ),
    ]
