# Generated by Django 4.2.16 on 2026-06-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0017_region_rank_change_alter_region_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Описание"
            ),
        ),
    ]
