version: 2
updates:
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: daily
      time: "18:00"
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/backend"
    schedule:
      interval: daily
      time: "18:00"
    open-pull-requests-limit: 10