version: "2"         # required to adjust maintainability checks
checks:
  similar-code:
    config:
      threshold: 120
exclude_patterns:
 - "config/"
 - "db/"
 - "dist/"
 - "features/"
 - "**/migrations/"
 - "**/node_modules/"
 - "script/"
 - "**/spec/"
 - "**/test/"
 - "**/tests/"
 - "Tests/"
 - "**/tests.py"
 - "**/vendor/"
 - "**/*_test.go"
 - "**/*.d.ts"
 - "acesta/static/js/bootstrap-strength-meter.js"
 - "acesta/static/js/password-score.js"
