# Generated by Django 3.2.16 on 2023-02-11 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20230210_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcitypopularity',
            name='modified_storage',
        ),
        migrations.RemoveField(
            model_name='allregionpopularity',
            name='modified_storage',
        ),
    ]
