# Generated by Django 3.2.16 on 2023-03-04 14:54

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20230211_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('update', models.CharField(choices=[('situation', 'Ситуация'), ('sights', 'Точки притяжения'), ('kernels', 'Ядра'), ('popularity', 'Популярность'), ('audience', 'Аудитория')], db_index=True, max_length=10, unique=True, verbose_name='Тип обновления')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Дата обновлений',
                'verbose_name_plural': 'Даты обновлений',
            },
        ),
    ]
