# Generated by Django 3.2.16 on 2023-03-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_updates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Updates',
            new_name='Update',
        ),
    ]
