# Generated by Django 3.2.16 on 2023-04-22 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20230402_1833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update',
        ),
    ]
