# Generated by Django 3.2.16 on 2023-04-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_delete_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='value_type',
            field=models.CharField(choices=[('average_salary', 'Средняя зарплата'), ('average_per_person', 'Средний доход на человека')], default='average_salary', max_length=30, verbose_name='Вид показателя'),
        ),
    ]
