# Generated by Django 3.2.16 on 2023-04-23 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_auto_20230423_1451'),
        ('stats', '0009_alter_salary_value_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcitypopularity',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_allcitypopularity', to='geo.city', verbose_name='Интересант'),
        ),
        migrations.AlterField(
            model_name='allcitypopularity',
            name='home_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_city_all_city_popularity', to='geo.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='allcitypopularity',
            name='sight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sight_all_city_popularity', to='geo.sight', verbose_name='Достопримечательность'),
        ),
        migrations.AlterField(
            model_name='allcitypopularity',
            name='source_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_region_all_city_popularity', to='geo.region', verbose_name='Регион-источник'),
        ),
        migrations.AlterField(
            model_name='allregionpopularity',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_allregionpopularity', to='geo.region', verbose_name='Интересант'),
        ),
        migrations.AlterField(
            model_name='allregionpopularity',
            name='home_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_region_all_region_popularity', to='geo.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='allregionpopularity',
            name='sight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sight_all_region_popularity', to='geo.sight', verbose_name='Достопримечательность'),
        ),
        migrations.AlterField(
            model_name='allregionpopularity',
            name='source_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_city_all_region_popularity', to='geo.city', verbose_name='Город-источник'),
        ),
        migrations.AlterField(
            model_name='citycitypopularity',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_citycitypopularity', to='geo.city', verbose_name='Интересант'),
        ),
        migrations.AlterField(
            model_name='citycitypopularity',
            name='home_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_city_city_popularities', to='geo.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='cityrating',
            name='city_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_cityrating', to='geo.city', verbose_name='Город-интересант'),
        ),
        migrations.AlterField(
            model_name='cityrating',
            name='home_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_city_cityratings', to='geo.city', verbose_name='Домашний город'),
        ),
        migrations.AlterField(
            model_name='cityrating',
            name='home_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_region_cityratings', to='geo.region', verbose_name='Домашний регион'),
        ),
        migrations.AlterField(
            model_name='cityrating',
            name='region_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_cityrating', to='geo.region', verbose_name='Регион-интересант'),
        ),
        migrations.AlterField(
            model_name='cityregionpopularity',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_cityregionpopularity', to='geo.region', verbose_name='Интересант'),
        ),
        migrations.AlterField(
            model_name='cityregionpopularity',
            name='home_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_city_region_popularities', to='geo.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='regioncitypopularity',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_regioncitypopularity', to='geo.city', verbose_name='Интересант'),
        ),
        migrations.AlterField(
            model_name='regioncitypopularity',
            name='home_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_region_city_popularities', to='geo.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='regionrating',
            name='city_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_regionrating', to='geo.city', verbose_name='Город-интересант'),
        ),
        migrations.AlterField(
            model_name='regionrating',
            name='home_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_region_regionratings', to='geo.region', verbose_name='Домашний регион'),
        ),
        migrations.AlterField(
            model_name='regionrating',
            name='region_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_regionrating', to='geo.region', verbose_name='Регион-интересант'),
        ),
        migrations.AlterField(
            model_name='regionregionpopularity',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_regionregionpopularity', to='geo.region', verbose_name='Интересант'),
        ),
        migrations.AlterField(
            model_name='regionregionpopularity',
            name='home_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_region_region_popularities', to='geo.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_salaries', to='geo.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='sightrating',
            name='city_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_sightrating', to='geo.city', verbose_name='Город-интересант'),
        ),
        migrations.AlterField(
            model_name='sightrating',
            name='region_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_sightrating', to='geo.region', verbose_name='Регион-интересант'),
        ),
        migrations.AlterField(
            model_name='sightrating',
            name='sight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sight_ratings', to='geo.sight', verbose_name='Достопримечательность'),
        ),
    ]
