# Generated by Django 3.2.16 on 2023-10-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_alter_sightgroup_name'),
        ('stats', '0012_auto_20230725_0512'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allcitypopularity',
            unique_together={('sight', 'home_code', 'code', 'source_code', 'sight_group')},
        ),
        migrations.AlterUniqueTogether(
            name='allregionpopularity',
            unique_together={('sight', 'home_code', 'code', 'source_city', 'sight_group')},
        ),
    ]
