# Generated by Django 3.2.16 on 2023-10-11 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_alter_sightgroup_name'),
        ('stats', '0013_auto_20231009_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcitypopularity',
            name='sight_group',
            field=models.ForeignKey(blank=True, max_length=15, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_allcitypopularity', to='geo.sightgroup', verbose_name='Вид достопримечательности'),
        ),
        migrations.AlterField(
            model_name='allregionpopularity',
            name='sight_group',
            field=models.ForeignKey(blank=True, max_length=15, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_allregionpopularity', to='geo.sightgroup', verbose_name='Вид достопримечательности'),
        ),
        migrations.AlterField(
            model_name='sightrating',
            name='sight_group',
            field=models.ForeignKey(blank=True, max_length=15, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_sightrating', to='geo.sightgroup', verbose_name='Вид достопримечательности'),
        ),
    ]
