# Generated by Django 4.2.16 on 2024-11-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0011_alter_sightgroup_name"),
        ("stats", "0014_auto_20231011_1516"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allcitypopularity",
            name="sight_group",
            field=models.ForeignKey(
                blank=True,
                max_length=15,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="group_%(class)s",
                to="geo.sightgroup",
                verbose_name="Вид достопримечательности",
            ),
        ),
        migrations.AlterField(
            model_name="allregionpopularity",
            name="sight_group",
            field=models.ForeignKey(
                blank=True,
                max_length=15,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="group_%(class)s",
                to="geo.sightgroup",
                verbose_name="Вид достопримечательности",
            ),
        ),
        migrations.AlterField(
            model_name="sightrating",
            name="sight_group",
            field=models.ForeignKey(
                blank=True,
                max_length=15,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="group_%(class)s",
                to="geo.sightgroup",
                verbose_name="Вид достопримечательности",
            ),
        ),
    ]
