# Generated by Django 4.2.16 on 2025-05-05 14:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0016_region_federal_district"),
        ("stats", "0015_alter_allcitypopularity_sight_group_and_more"),
    ]
    #
    # operations = [
    #     migrations.CreateModel(
    #         name="AvgBill",
    #         fields=[
    #             (
    #                 "id",
    #                 models.BigAutoField(
    #                     auto_created=True,
    #                     primary_key=True,
    #                     serialize=False,
    #                     verbose_name="ID",
    #                 ),
    #             ),
    #             (
    #                 "created",
    #                 model_utils.fields.AutoCreatedField(
    #                     default=django.utils.timezone.now,
    #                     editable=False,
    #                     verbose_name="created",
    #                 ),
    #             ),
    #             (
    #                 "modified",
    #                 model_utils.fields.AutoLastModifiedField(
    #                     default=django.utils.timezone.now,
    #                     editable=False,
    #                     verbose_name="modified",
    #                 ),
    #             ),
    #             (
    #                 "avg_bill",
    #                 models.IntegerField(default=0, verbose_name="Средний чек"),
    #             ),
    #             (
    #                 "avg_bill_change",
    #                 models.FloatField(default=0.0, verbose_name="Изменение (%)"),
    #             ),
    #             (
    #                 "code",
    #                 models.ForeignKey(
    #                     on_delete=django.db.models.deletion.CASCADE,
    #                     related_name="region_avg_bills",
    #                     to="geo.region",
    #                     verbose_name="Регион",
    #                 ),
    #             ),
    #         ],
    #         options={
    #             "verbose_name": "Средний чек",
    #             "verbose_name_plural": "Средний чек",
    #         },
    #     ),
    # ]
