# Generated by Django 4.2.16 on 2025-05-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0016_region_federal_district"),
        ("stats", "0016_avgbill"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="salary",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="salary",
            name="month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                    (12, 12),
                ],
                null=True,
                verbose_name="Месяц",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salary",
            unique_together={("code", "value_type", "month", "quarter", "year")},
        ),
    ]
