# Generated by Django 4.2.16 on 2025-05-06 05:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0016_region_federal_district"),
        ("stats", "0017_alter_salary_unique_together_salary_month_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("average_salary", "Средняя начисленная зарплата"),
                            ("average_bill", "Средний чек"),
                            ("average_per_person", "Средний доход на человека"),
                        ],
                        default="average_salary",
                        max_length=30,
                        verbose_name="Вид показателя",
                    ),
                ),
                (
                    "quarter",
                    models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], verbose_name="Квартал"),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                        ],
                        null=True,
                        verbose_name="Месяц",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (2019, 2019),
                            (2020, 2020),
                            (2021, 2021),
                            (2022, 2022),
                            (2023, 2023),
                            (2024, 2024),
                            (2025, 2025),
                            (2026, 2026),
                            (2027, 2027),
                            (2028, 2028),
                            (2029, 2029),
                            (2030, 2030),
                        ],
                        verbose_name="Год",
                    ),
                ),
                ("value", models.FloatField(default=0.0, verbose_name="Значение")),
                ("change", models.FloatField(default=0.0, verbose_name="Изменение")),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="region_salaries",
                        to="geo.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Экономические показатели",
                "verbose_name_plural": "Экономические показатели",
                "ordering": ("-year", "-quarter", "code"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="salary",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="salary",
            name="code",
        ),
        # migrations.DeleteModel(
        #     name="AvgBill",
        # ),
        migrations.DeleteModel(
            name="Salary",
        ),
        migrations.AddIndex(
            model_name="indicator",
            index=models.Index(
                fields=["value_type", "quarter", "year"],
                name="stats_indic_value_t_53b091_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="indicator",
            unique_together={("code", "value_type", "month", "quarter", "year")},
        ),
    ]
