# Generated by Django 4.2.16 on 2026-03-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0016_region_federal_district"),
        ("stats", "0018_indicator_alter_salary_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="allcitypopularity",
            unique_together={
                ("sight", "code", "source_code", "sight_group"),
                ("sight", "home_code", "code", "source_code", "sight_group"),
            },
        ),
    ]
