# Generated by Django 3.2.16 on 2023-04-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230402_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ['-modified'], 'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterField(
            model_name='support',
            name='subject',
            field=models.CharField(choices=[('support', 'Обращение в техподдержку'), ('report', 'Заказ отчета'), ('sights', 'Новые достопримечательности')], max_length=10, verbose_name='Тема'),
        ),
    ]
