# Generated by Django 3.2.16 on 2023-04-23 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20230423_1349'),
        ('user', '0004_auto_20230422_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='region_orders', to='geo.Region', verbose_name='Регионы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='support',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geo.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_region_users', to='geo.region', verbose_name='Последний регион'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_region_users', to='geo.region', verbose_name='Домашний регион'),
        ),
        migrations.AlterField(
            model_name='user',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='paid_regions_users', to='geo.Region', verbose_name='Оплаченные регионы'),
        ),
    ]
