# Generated by Django 3.2.16 on 2023-04-30 11:51

import acesta.user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230423_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[acesta.user.validators.validate_russian], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[acesta.user.validators.validate_russian], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=50, validators=[acesta.user.validators.validate_russian], verbose_name='Отчество'),
        ),
    ]
