# Generated by Django 3.2.16 on 2023-07-04 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230430_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('channel', models.CharField(choices=[('phone', 'Телефон'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('viber', 'Viber')], max_length=10, verbose_name='Канал связи')),
                ('_id', models.CharField(max_length=20, verbose_name='Номер или ник')),
                ('subject', models.CharField(choices=[('consultation', 'Консультация'), ('presentation', 'Презентация')], max_length=15, verbose_name='Тема')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('note', models.CharField(max_length=255, verbose_name='Заметки')),
                ('state', models.CharField(choices=[('new', 'новая'), ('waiting', 'в ожидании'), ('done', 'обработан')], default='new', max_length=10, verbose_name='Статус')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запросы',
                'verbose_name_plural': 'Запросы',
                'ordering': ['-modified'],
            },
        ),
    ]
