# Generated by Django 3.2.16 on 2023-07-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='request',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='subject',
            field=models.CharField(choices=[('consultation', 'Консультация'), ('presentation', 'Презентация')], default='consultation', max_length=15, verbose_name='Тема'),
        ),
    ]
