# Generated by Django 3.2.16 on 2023-07-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_request_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.SmallIntegerField(default=0, verbose_name='Контакты'),
        ),
    ]
