# Generated by Django 3.2.16 on 2023-07-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок'),
        ),
    ]
