# Generated by Django 4.2.3 on 2023-07-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_request_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="channel",
            field=models.CharField(
                choices=[
                    ("phone", "Телефон"),
                    ("telegram", "Telegram"),
                    ("whatsapp", "WhatsApp"),
                    ("viber", "Viber"),
                    ("viber", "VK"),
                    ("facebook", "Facebook"),
                    ("email", "Email"),
                ],
                max_length=10,
                verbose_name="Канал связи",
            ),
        ),
    ]
