# Generated by Django 4.2.3 on 2023-07-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_alter_request_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="_id",
            field=models.CharField(max_length=32, verbose_name="Номер или ник"),
        ),
        migrations.AlterField(
            model_name="request",
            name="channel",
            field=models.CharField(
                choices=[
                    ("phone", "Телефон"),
                    ("telegram", "Telegram"),
                    ("whatsapp", "WhatsApp"),
                    ("viber", "Viber"),
                    ("vk", "VK"),
                    ("facebook", "Facebook"),
                    ("email", "Email"),
                ],
                max_length=10,
                verbose_name="Канал связи",
            ),
        ),
    ]
