# Generated by Django 3.2.16 on 2023-07-10 04:24

import acesta.user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_request__id_alter_request_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=35, validators=[acesta.user.validators.validate_russian], verbose_name='Имя'),
        ),
    ]
