# Generated by Django 3.2.16 on 2023-07-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_auto_20230710_1806'),
        ('user', '0015_alter_request_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='interest',
            field=models.BooleanField(default=True, verbose_name='Интерес'),
        ),
        migrations.AddField(
            model_name='request',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_requests', to='geo.region', verbose_name='Регион'),
        ),
    ]
