# Generated by Django 3.2.16 on 2023-07-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20230718_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=12, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
