# Generated by Django 3.2.16 on 2023-07-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заметки'),
        ),
    ]
