# Generated by Django 3.2.16 on 2023-07-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_hit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний хит'),
        ),
    ]
