# Generated by Django 3.2.16 on 2023-07-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_user_last_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Промокод'),
        ),
    ]
