# Generated by Django 3.2.16 on 2023-07-28 14:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20230728_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tourism_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('gastro', 'гастротуризм'), ('museum', 'музейный туризм'), ('spa', 'оздоровительный туризм'), ('beach', 'пляжный туризм'), ('industry', 'промышленный туризм'), ('outdoor', 'развлекательный туризм'), ('pilgrimage', 'религиозный туризм'), ('extreme', 'спортивный туризм'), ('theatre', 'театральный туризм'), ('shopping', 'шопинг-туризм'), ('recreation', 'экологический туризм'), ('excursion', 'экскурсионный туризм')], max_length=10, verbose_name='Виды туризма'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='period',
            field=models.FloatField(choices=[(0.25, '1 неделя'), (0.5, '2 недели'), (1, '1 месяц'), (2, '2 месяца'), (3, '3 месяца'), (4, '4 месяца'), (5, '5 месяцев'), (6, '6 месяцев'), (12, '12 месяцев')], verbose_name='Период'),
        ),
    ]
