# Generated by Django 3.2.16 on 2023-07-28 16:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20230728_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tourism_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('gastro', 'гастротуризм'), ('museum', 'музейный туризм'), ('spa', 'оздоровительный туризм'), ('beach', 'пляжный туризм'), ('industry', 'промышленный туризм'), ('outdoor', 'развлекательный туризм'), ('pilgrimage', 'религиозный туризм'), ('extreme', 'спортивный туризм'), ('theatre', 'театральный туризм'), ('shopping', 'шопинг-туризм'), ('recreation', 'экологический туризм'), ('excursion', 'экскурсионный туризм')], max_length=10, verbose_name='Оплаченные виды туризма'), blank=True, null=True, size=None),
        ),
    ]
