# Generated by Django 3.2.16 on 2023-07-29 11:49

import acesta.user.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_alter_region_options'),
        ('user', '0027_auto_20230729_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[acesta.user.validators.validate_russian], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[acesta.user.validators.validate_russian], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_region_users', to='geo.region', verbose_name='Домашний регион'),
        ),
    ]
