# Generated by Django 3.2.16 on 2023-07-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='purpose',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='Цель'),
        ),
    ]
