# Generated by Django 3.2.16 on 2023-07-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_user_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.BooleanField(default=False, verbose_name='Регистрация завершена'),
        ),
    ]
