# Generated by Django 4.2.16 on 2024-11-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0031_user_registered"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="segment",
            field=models.CharField(
                choices=[
                    ("undefined", "Не определен"),
                    ("government", "Органы власти"),
                    ("tic", "Туристско-информационные центры"),
                    ("tour-operator", "Туроператоры"),
                    ("tour-agent", "Турагенты"),
                    ("tourism-product-owner", "Владельцы бизнеса"),
                    ("marketing-agency", "Маркетинговые агентства"),
                ],
                default="undefined",
                max_length=25,
            ),
        ),
    ]
