# Generated by Django 4.2.16 on 2025-04-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0032_user_segment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="segment",
            field=models.CharField(
                choices=[
                    ("undefined", "Не определен"),
                    (
                        "government",
                        "Государственные организации и туристические ассоциации",
                    ),
                    ("tic", "Туристско-информационные центры (ТИЦ)"),
                    ("tour-operator", "Туроператоры"),
                    ("tour-agent", "Турагенты"),
                    ("tourism-product-owner", "Владельцы бизнеса в туризме"),
                    ("tourist-investor", "Инвесторы в туристическую отрасль"),
                    ("tourist-guide", "Экскурсоводы и гиды"),
                    ("marketing-agency", "Маркетинговые агентства"),
                    ("hospitality", "Отели и гостиничные сети"),
                    ("tourism-event", "Организаторы событийного туризма"),
                    ("transport", "Авиакомпании и транспортные компании"),
                ],
                default="undefined",
                max_length=25,
            ),
        ),
    ]
