# Generated by Django 4.2.16 on 2025-05-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0033_alter_user_segment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="federal_district",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ЦФО", "Центральный"),
                    ("СЗФО", "Северо-Западный"),
                    ("ЮФО", "Южный"),
                    ("СКФО", "Северо-Кавказский"),
                    ("ПФО", "Приволжский"),
                    ("УрФО", "Уральский"),
                    ("СФО", "Сибирский"),
                    ("ДФО", "Дальневосточный"),
                ],
                max_length=4,
                null=True,
                verbose_name="Федеральный округ",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="segment",
            field=models.CharField(
                choices=[
                    ("undefined", "Профессионалы туриндустрии"),
                    ("government", "Эксперты государственного управления туризма"),
                    ("tic", "Специалисты туристско-информационных центров (ТИЦ)"),
                    ("tour-operator", "Туроператоры и проектировщики маршрутов"),
                    ("tour-agent", "Турагенты и консультанты по путешествиям"),
                    (
                        "tourism-product-owner",
                        "Предприниматели и владельцы бизнеса в туризме",
                    ),
                    ("tourist-investor", "Инвесторы и партнеры туризма"),
                    ("tourist-guide", "Экскурсоводы и гиды"),
                    ("marketing-agency", "Маркетологи и PR-специалисты туризма"),
                    ("hospitality", "Специалисты гостиничного бизнеса"),
                    ("tourism-event", "Организаторы туристических событий"),
                    ("transportation", "Эксперты авиа- и транспортных компаний"),
                ],
                default="undefined",
                max_length=25,
            ),
        ),
    ]
