# Generated by Django 4.2.16 on 2025-05-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0034_order_federal_district_alter_user_segment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="segment",
            field=models.CharField(
                choices=[
                    ("undefined", "Профессионалы туриндустрии"),
                    ("government", "Эксперты государственного управления в туризме"),
                    ("tic", "Специалисты туристско-информационных центров (ТИЦ)"),
                    ("tour-operator", "Туроператоры и проектировщики маршрутов"),
                    ("tour-agent", "Турагенты и консультанты по путешествиям"),
                    (
                        "tourism-product-owner",
                        "Предприниматели и владельцы бизнеса в туризме",
                    ),
                    ("tourist-investor", "Инвесторы и партнеры туризма"),
                    ("tourist-guide", "Экскурсоводы и гиды"),
                    ("marketing-agency", "Маркетологи и PR-специалисты в туризме"),
                    ("hospitality", "Специалисты гостиничного бизнеса"),
                    ("tourism-event", "Организаторы мероприятий в туризме"),
                    ("transportation", "Эксперты авиа- и транспортных компаний"),
                ],
                default="undefined",
                max_length=25,
            ),
        ),
    ]
