# Generated by Django 4.2.16 on 2026-03-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0035_alter_user_segment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="channel",
            field=models.CharField(
                choices=[
                    ("phone", "Телефон"),
                    ("telegram", "Telegram"),
                    ("whatsapp", "WhatsApp"),
                    ("viber", "Viber"),
                    ("vk", "VK"),
                    ("facebook", "Facebook"),
                    ("email", "Email"),
                    ("max", "Max"),
                ],
                max_length=10,
                verbose_name="Канал связи",
            ),
        ),
    ]
