# Generated by Django 4.2.16 on 2026-03-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0036_alter_request_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hidden_last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Скрытая фамилия"
            ),
        ),
    ]
